// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oybwcprzohbijocjsdir.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im95YndjcHJ6b2hiaWpvY2pzZGlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzgyNjQyMjcsImV4cCI6MjA5Mzg0MDIyN30.Q3G-UtXCiniuOElx3WP5B9zqs-cANaome1vsjwyMHkM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});